language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/3.0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/3.1.gemfile
    - rvm: 2.2
      gemfile: gemfiles/3.2.gemfile
